[debug] [2025-01-09T07:30:30.186Z] : 
[debug] [2025-01-09T07:30:30.190Z] : ----------------------------------------------------------------------
[debug] [2025-01-09T07:30:30.191Z] : Command:      C:\Program Files\nodejs\node.exe C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\bin\catalyst.js deploy
[debug] [2025-01-09T07:30:30.191Z] : CLI Version:  1.17.6
[debug] [2025-01-09T07:30:30.192Z] : Platform:     win32
[debug] [2025-01-09T07:30:30.192Z] : Node Version: v20.15.1
[debug] [2025-01-09T07:30:30.193Z] : Time:         Thu Jan 09 2025 13:00:30 GMT+0530 (India Standard Time)
[debug] [2025-01-09T07:30:30.193Z] : ----------------------------------------------------------------------
[debug] [2025-01-09T07:30:30.193Z] : 
[debug] [2025-01-09T07:30:33.158Z] : > authorizing via signed-in user option
[debug] [2025-01-09T07:30:33.159Z] : > command requires scopes: ["ZohoCatalyst.projects.ALL","ZohoCatalyst.functions.ALL","ZohoCatalyst.webapp.ALL","ZohoCatalyst.appsail.Update"]
[debug] [2025-01-09T07:30:33.189Z] : > refreshing access token <
[debug] [2025-01-09T07:30:33.192Z] : >>>> HTTP REQUEST : POST https://accounts.zoho.in/oauth/v2/token 
<request body omitted>

[warn] [2025-01-09T07:30:33.490Z] : ‼ ENOTFOUND has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2025-01-09T07:30:33.491Z] : API Error while firing request : getaddrinfo ENOTFOUND accounts.zoho.in

[debug] [2025-01-09T07:30:33.491Z] : >>>> RETRYING

[warn] [2025-01-09T07:30:33.507Z] : ‼ ENOTFOUND has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2025-01-09T07:30:33.508Z] : API Error while firing request : getaddrinfo ENOTFOUND accounts.zoho.in

[debug] [2025-01-09T07:30:33.508Z] : >>>> RETRYING

[warn] [2025-01-09T07:30:33.516Z] : ‼ ENOTFOUND has occured while communicating remote server. Kindly be patient while the cli retries this request.
[debug] [2025-01-09T07:30:33.516Z] : API Error while firing request : getaddrinfo ENOTFOUND accounts.zoho.in

[debug] [2025-01-09T07:30:33.516Z] : >>>> RETRYING

[warn] [2025-01-09T07:30:33.525Z] : ‼ ENOTFOUND has occured while communicating remote server. Kindly be patient while the cli retries this request.
[error] [2025-01-09T07:30:33.550Z] : × API Error after retrying : getaddrinfo ENOTFOUND accounts.zoho.in
[debug] [2025-01-09T07:30:33.550Z] : Error Stack: CatalystError: API Error after retrying : getaddrinfo ENOTFOUND accounts.zoho.in
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:162:23)
    at Generator.next (<anonymous>)
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:27:12)
    at API._retry (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:160:16)
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:205:56)
    at Generator.next (<anonymous>)
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
[debug] [2025-01-09T07:30:33.550Z] : Original Error: Error: getaddrinfo ENOTFOUND accounts.zoho.in
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[debug] [2025-01-09T07:30:33.551Z] : Error Status: 500
[info] [2025-01-09T07:30:33.552Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2025-01-09T07:30:33.553Z] : × API Error: getaddrinfo ENOTFOUND accounts.zoho.in
[debug] [2025-01-09T07:30:33.553Z] : Error Stack: CatalystError: API Error: getaddrinfo ENOTFOUND accounts.zoho.in
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:214:32)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2025-01-09T07:30:33.556Z] : Original Error: Error: getaddrinfo ENOTFOUND accounts.zoho.in
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[debug] [2025-01-09T07:30:33.556Z] : Error Status: 500
[info] [2025-01-09T07:30:33.558Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2025-01-09T07:30:33.560Z] : × API Error: getaddrinfo ENOTFOUND accounts.zoho.in
[debug] [2025-01-09T07:30:33.560Z] : Error Stack: CatalystError: API Error: getaddrinfo ENOTFOUND accounts.zoho.in
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:214:32)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2025-01-09T07:30:33.560Z] : Original Error: Error: getaddrinfo ENOTFOUND accounts.zoho.in
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[debug] [2025-01-09T07:30:33.561Z] : Error Status: 500
[info] [2025-01-09T07:30:33.562Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[error] [2025-01-09T07:30:33.577Z] : × Error when refreshing the access token
[debug] [2025-01-09T07:30:33.577Z] : Error Stack: CatalystError: Error when refreshing the access token
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\credential.js:139:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2025-01-09T07:30:33.578Z] : Original Error: CatalystError: API Error after retrying : getaddrinfo ENOTFOUND accounts.zoho.in
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:162:23)
    at Generator.next (<anonymous>)
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:27:12)
    at API._retry (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:160:16)
    at API.<anonymous> (C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:205:56)
    at Generator.next (<anonymous>)
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\zcatalyst-cli\lib\internal\api.js:31:71
    at new Promise (<anonymous>)
[debug] [2025-01-09T07:30:33.578Z] : Error Status: 500
[info] [2025-01-09T07:30:33.579Z] : Kindly contact Catalyst support [support@zohocatalyst.com] if you need any further assistance
[debug] [2025-01-09T07:30:33.581Z] : EXEC ENDED with event: Error (Unexpected), message: Error when refreshing the access token
[debug] [2025-01-09T07:30:33.581Z] : TOTAL DURATION OF COMMAND EXEC : 419
[debug] [2025-01-09T07:30:33.582Z] : Unable to initialise the log API
